name: Scheduled Data Update

on:
  schedule:
  - cron: "5 8 * * *"

jobs:
  runDataUpdate:
    name: Run Data Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Data Update
      uses: ./_action-update
      env:
        BRANCH_NAME: master
        BOT_USER: usnistgov
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
